Maven Central Migration - Library updates to fix build
davideas/FlexibleAdapter pull request #770
Opened 2021-03-05 16:26 UTC by lauren2020

Issue: #768 

This PR updates outdated dependencies that were preventing the project from building and being moved to maven central.

The demo app included in this repo is NOT fixed with these changes. The source of the build failure for flexible-adapter-app is setting items in a recycler view on line 34 of fragment_recycler_view_data.xml - creating a separate PR for this issue to keep in scope of dependency updates.

2021-03-05 16:41 UTC, barnhill requested changes

2021-03-05 16:41 UTC, barnhill commented on build.gradle
> +        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:$build_info_extractor_gradle_version"
Jfrog is JCenter so we should try to remove all their stuff

2021-03-05 16:41 UTC, barnhill commented on flexible-adapter/build.gradle
> +    //apply from: '../jfrog-bintray-publish.gradle'
Remove this as it's JCenter

2021-03-05 16:41 UTC, barnhill commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https://services.gradle.org/distributions/gradle-6.7.1-all.zip
6.8.3 is out

2021-03-05 16:41 UTC, barnhill commented on build.gradle
> +        buildTools = "29.0.2"
This is no longer needed as it's included in the Gradle plugin now

2021-03-05 16:41 UTC, barnhill commented on build.gradle
>          maven { url "http://dl.bintray.com/davideas/maven" }
This is a JCenter url.

2021-03-10 17:59 UTC, lauren2020 commented on flexible-adapter-app/src/main/res/layout/fragment_recycler_view_data.xml
> +                <!-- app:items="@{items}" was causing build error, temporarily removed -->
This was causing a build error for the demo app, would like to move fix for demo app to a separate pr to not hold up general build fix for maven central migration

2021-04-11 10:12 UTC, merged

2021-04-11 21:18 UTC, barnhill commented
gradlepluginportal() may point to JCenter too. We need to eval if this is necessary.